### ISSUE TITLE
Tumor only variant calling

### ISSUE THREAD

**Issue by kokyriakidis** [genetronhealth/uvc#5]
Hi!

Do you have any recent benchmarks regarding Tummor only variant calling? I was about to try Mutect and PureCN when I saw your implementation.

Thanks,
Konstantinos

**Comment by genetronhealth** [comment]
Hi!

All benchmark results about tumor-only variant calling are in the supplemental results section 1.3 (https://www.biorxiv.org/content/biorxiv/early/2021/02/22/2020.08.23.263749/DC2/embed/media-2.pdf?download=true page 13). 
Please note that I did not exclude germline variants from the ground truth, meaning that both germline and somatic variants are called by the evaluated tools. If you would like to call only somatic variants from tumor-only data, then you should consider using a germline-variant database such as the 1000genome database. According to our experience, germline-variant database can get rid of a lot of germline variants. After running UVC, we used PureCN and GATK panel-of-normal for detecting CNV and estimating purity ploidy, and our tumor-only somatic variant-calling pipeline is also fairly accurate (our preliminary results show that our tumor-only pipeline outputs the same tumor-mutation-burden (TMB) over 3MB of genomic region as the tumor-normal-paired pipeline for the majority of samples).

If you have any other question, please let me know.
Xiaofei

**Comment by kokyriakidis** [comment]
Hi!

Thank you for the info. Do you think it is better to use tumor only approach or use a similarly prepared sample from another individual?

**Comment by genetronhealth** [comment]
Hi!

You are welcome! It depends on what you would like to achieve in the end. Do you care about determining whether the variant is of germline or somatic origin? If you are only interested in driver mutations, then you do not need to determine the germline-vs-somatic origin of the variant. If you want to compute tumor mutation burden, then you have to determine the germline-vs-somatic origin. 

In any case, having the sequencing data from another individual always helps if used correctly because some sequencing artifact can be eliminated by using such data.

**Comment by genetronhealth** [comment]
@kokyriakidis  Hi, I answered your question a few months ago, do you have any other questions? If your questions are all answered, then will close this issue.

**Comment by kokyriakidis** [comment]
Its all good! Thanks!
